### ISSUE TITLE
Why are you set default locale to de_DE.UTF-8 ?

### ISSUE THREAD

**Issue by gratuxri** [LinuxHaus/ansible_lihas_common#1]
It's dependency from proxmox role.
It's more reasonable to set it to en_US.UTF-8, like proxmox people are doing this.

**Comment by areyer** [comment]
Because I am in Germany.
Proxmox works perfectly fine with de_DE.UTF-8 and if it doesn't it is worth a bug report there for sure.
If you want to change to other locales you can do so now by setting variables, e.g.
locales_default_environment_locale: en_US.UTF-8
locales_locales_to_be_generated:
  - de_DE.UTF-8
  - en_US.UTF-8

**Comment by gratuxri** [comment]
Thank you, on server instances it' sometimes usefully to habe en_US or C as default, because of searching for english errors brings more search results by different search engines.
